# Site
name: "GREENAGE"
title: "GREENAGE"
description: "The official community portal of Salarpuria Sattva Greenage."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/


# Authors
authors:
  Admin:
    name: Greenage
    display_name: Greenage
    gravatar: 
    email: 
    web: 
    twitter: 
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 18
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  - scope:
      path: '_redirect'
      type: 'pages'
    values:
      layout: 'redirect'
collections:
  redirect:
    output: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE.*
  - README.*

# Google Analytics
google_analytics: G-9GC87LCFVC